### ISSUE TITLE
Adsorption capacity calculated from area under the breakthrough curve is more than the used qm value of Langmuir equation.

### ISSUE THREAD

**Issue by sptiwari** [iRASPA/RUPTURA#4]
I have the following simulation.input file:  
[Simulation Input File](https://gist.github.com/sptiwari/bb7e9e62ba574817440d8d6f511ab4c3)  

Using this file, I obtained the following breakthrough curve for CO2:  
[Breakthrough Curve](https://gist.github.com/sptiwari/cb4493e8454bc7e38c2ced94ca7009c0)  

To calculate the maximum adsorption capacity from the area under the curve, I used the following Python script:  
[Python Script](https://gist.github.com/sptiwari/69731c827bde7c63b9043c79e2876e04)  

The script provides a value of 4.1572 mol/kg, which is higher than the qm value of 2.858 mol/kg used in the simulation input file.  

Why am I getting a higher value? Is this a bug, or am I doing something wrong?

**Comment by dubbelda** [comment]
The loadings in the columns are stored, in variable 'Q'. If you plot the movie 'column_movie_Q.mp4' you can see how they converge to the equilibrium values. These equilibrium mixture loading in the column are equal to the value in the mixture isotherms. They do not exceed the saturation values.
Integrating from the outlet is difficult for step-breakthroughs (we did check this for pulse where it makes more sense).
for example, line 40 in your script is only valid at the inlet, and the velocity varies over the column.

**Comment by sptiwari** [comment]
Thank you for your insightful response. This is very helpful, and I now understand that the issue lies in the velocity variation across the column.

However, I am unable to view the slide you shared. Could you please share it again?

Thank you.
